import * as fs from 'fs';
import * as path from 'path';
import { GraphQLSchema } from 'graphql'
import { GenerateTypescriptOptions, defaultOptions } from './types';
import { TypeScriptGenerator } from './typescriptGenerator';

const packageJson = require(path.join(__dirname, '../package.json'));

export const generateTypeScriptTypes = async (schema: GraphQLSchema, outputPath: string, options: GenerateTypescriptOptions = defaultOptions) => {
    const tsGenerator = new TypeScriptGenerator({ ...defaultOptions, ...options });
    const typeDefs = await tsGenerator.generate(schema);

    const jsDoc = 
`/**
 * This file is auto-generated by ${packageJson.name}@${packageJson.version}
 * Please note that any changes in this file may be overwritten
 */
`;
    fs.writeFileSync(outputPath, [jsDoc, typeDefs].join('\n'), 'utf-8');
};